server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://192.168.1.45/game?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: aHNOjqtl%pKp